[package]
name = "scoc"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Spar Command Output Converter"
repository = "https://github.com/oraclevs/scoc"

[dependencies]
chrono = { version = "0.4", default-features = true }
regex = "1"
serde_json = { version = "1", features = ["preserve_order"] }
thiserror = "2"

[dev-dependencies]
serde_json = { version = "1", features = ["preserve_order"] }
